### ISSUE TITLE
[Bug] Readthedocs is not working

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#49]
The readthedocs is not working. Please use [this](https://github.com/rl-institut/mvs_eland/tree/dev/docs) as a reference on what might be wrong - basically, the structure should be the same in Offgridders.

**Comment by smartie2076** [comment]
Nice to have you in the project now, @santiagoinfantinom ! I think this would be the best task to start off with (after you have red some stuff about the tool in #52), and then you can continue with #53. If I am working on that still, you can instead work on #41.

**Comment by santiagoinfantinom** [comment]
Hi @smartie2076, I don't know what I am missing here but after making the html, everything works just fine. The documentation is from mvs_eland but works properly,as far as I can tell.. I'm gonna move to #41 for the moment and start migrating the wiki info in my local branch

**Comment by smartie2076** [comment]
Hi @santiagoinfantinom! That is quite strange, as the online version [https://offgridders.readthedocs.io/en/latest/](https://offgridders.readthedocs.io/en/latest/) is not working properly. You have not done any changes that you can push?
