### ISSUE TITLE
[Documentation] General information on Offgridders

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#52]
Here, we should gather all information that connected to Offgridders so that we can translate it into a readthedocs in the future.

Available info:
- Presentation on how to use Offgridders / MST V1
- Excerpt of Martha Hoffmann´s master thesis on Offgridders functionalities
- Paper using Offgridders
- Updated list on current publications with Offgridders
- Link to a GUI for Offgridders

**Comment by smartie2076** [comment]
**Presentation on how to use Offgridders**

This presentation describes how to use Offgridders intermediary development versions, ie. V1. There have been a couple of changes by now (most importantly, that there is now an AC and a DC bus, see master thesis excerpt), also comp. the [CHANGELOG.md](https://github.com/rl-institut/offgridders/blob/dev/CHANGELOG.md), so please keep in mind that we are by now at V3!

[Presentation Offgridders V1 (2019-03-28)](https://github.com/rl-institut/offgridders/files/4415265/MGT_Tutorial_Mar28.pdf)

**Comment by smartie2076** [comment]
**Master thesis excerpt**
The master thesis 
[Master thesis excerpt on Offgridders, M. Hoffmann 2019](https://github.com/rl-institut/offgridders/files/4415276/oesmot_description_hoffmann_rli.pdf)

**Comment by smartie2076** [comment]
**Journal paper using Offgridders: Backup systems for unreliable grids**

Hoffmann MM, Pelz S, Monés-Pederzini Ò, Andreottola   M, Blechinger P. Overcoming the Bottleneck of Unreliable Grids: Increasing   Reliability of Household Supply with Decentralized Backup Systems. J Sustain   Res. 2020;2(1):e200009. https://doi.org/10.20900/jsr20200009

[Open Source Journal Paper](https://sustainability.hapres.com/htmls/JSR_1173_Detail.html)

**Comment by smartie2076** [comment]
** Graphical User Interface of Offgridders (limited functionalities)*

The Off-Grid Test Center developed a web-interface for Offgridders, allowing easy system optimization with few inputs. 

[It is available on their web-page](http://offgridtestcenter.nl/assessment-tool/#/)

**Comment by smartie2076** [comment]
Current publication projects using Offgridders:
- Paul Bertheau, Martha M. Hoffmann, Andrea Eras-Almeida, Philipp Blechinger: *Assessment of micro grid potential in Southeast Asia based on the application of geospatial and micro grid simulation and planning tools. In:  Sustainable solutions for remote areas in the tropics.* Editor: Octoviano   Ghandi, Dipti Srinivasan.
- *Supplying not electrified island with 100% renewable energy based micro grids: A geospatial and techno-economic analysis for the Philippines*, Paul Bertheau
- *Multicriteria-based methodology for the design of rural electrification systems. A case study in Nigeria*, Marc Juanpera, Philipp Blechinger, Laia Ferrer-Martí, Martha M. Hoffmann, Rafael Pastor, 2020, submitted to the Journal "Renewable Energy and Sustainable Reviews"

**Comment by smartie2076** [comment]
**Book chapter: Featuring comparison of Offgridders to other tools**

Paul Bertheau, Martha M. Hoffmann, Andrea Eras-Almeida, Philipp Blechinger: *Assessment of micro grid potential in Southeast Asia based on the application of geospatial and micro grid simulation and planning tools*. In: Sustainable solutions for remote areas in the tropics. Editor: Octoviano Ghandi, Dipti Srinivasan.

Preview available at: [Springer Link](https://www.springer.com/gp/book/9783030419516#aboutBook)

**Comment by smartie2076** [comment]
**Journal paper: Using Offgridders for analysis of a great number of locations**

Paul Bertheau: *Supplying not electrified island with 100% renewable energy based micro grids: A geospatial and techno-economic analysis for the Philippines*, Energy, July 2020

Link to paper: [Sciencedirect](https://www.sciencedirect.com/science/article/abs/pii/S0360544220307775?dgcid=author)

**Comment by smartie2076** [comment]
**[Submitted] Journal paper: Integration of Multi-Criteria Analysis into Offgridders**

Marc Juanpera, Philipp Blechinger, Laia Ferrer-Martí, Martha M. Hoffmann, Rafael Pastor: *Multicriteria-based methodology for the design of rural electrification systems. A case study in Nigeria*,  2020, submitted to the Journal "Renewable & Sustainable Energy Reviews" 

This paper will give an overview over the new futures realized in PR #47.

**Comment by smartie2076** [comment]
@santiagoinfantinom can you translate this issue into an rst file?

**Comment by santiagoinfantinom** [comment]
@santiagoinfantinom create page by rdd  "Literature"
