### ISSUE TITLE
Travis does not update

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#56]
When creating a PR, travis runs and tests the branch. The tests also run through:

![image](https://user-images.githubusercontent.com/44204527/80760928-f64f2480-8b39-11ea-9000-89361f16ad54.png)

![image](https://user-images.githubusercontent.com/44204527/80760947-fe0ec900-8b39-11ea-9433-73e7ae3c453e.png)

Still, the test status is not updated in the PR request itself. What has to be changed?

https://github.com/rl-institut/offgridders/pull/54
![image](https://user-images.githubusercontent.com/44204527/80761016-154db680-8b3a-11ea-861b-0bf622b29b04.png)

**Comment by smartie2076** [comment]
@Bachibouzouk do you know why this does not run through... or at least doesn't update on github? I think it was the same with the MVS at some point...

I went with my gut and local tests/looking at the travis website for now, and I just hope that the last release went through smoothly...

**Comment by Bachibouzouk** [comment]
@smartie2076  - you had it as your private repository, thus Travis from rl-institut was not activated (you have to go to the organization settings and allow Travis for your repository, which I did), it should solve itself for the next PRs (maybe need to go back to the branch option and tick off the current travis option and select the two new ones)

**Comment by smartie2076** [comment]
Thank you @Bachibouzouk ! I will check if it works when the next PR is open. Will see then, if I have to tick on/off the travis options (not sure where to do that yet) - and if it works I will close this issue :)

**Comment by Bachibouzouk** [comment]
Settings -> branches -> edit the branch rules - > Require status checks to pass before merging

**Comment by smartie2076** [comment]
Hmhm... I have a PR request at hand and therefore wanted to follow up with this issue. However, I can not check the "new travis tests". Do you know what´s going on here @Bachibouzouk ? You have admin rights and should be able to look into the repro settings, too.

![grafik](https://user-images.githubusercontent.com/44204527/82796148-5c974080-9e75-11ea-9a79-0977663bb0d6.png)

**Comment by Bachibouzouk** [comment]
I have unchecked it, I think it will update by the next PR, the check runs on travis but are not reported on github. The "continuous-integration/travis-ci" is a [known bug](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154)

**Comment by smartie2076** [comment]
The travis tests run though now.
