### ISSUE TITLE
Wiki on github needs to be removed

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#63]
To avoid a double structure with the readthedocs, can you @santiagoinfantinom delete all the Wiki entries on github? Make sure, that you copied there info into the new readthedocs before deleting!

For that, you go to the different headers in the index of the wiki and edit the pages:
![grafik](https://user-images.githubusercontent.com/44204527/82872087-d6413400-9f32-11ea-95d5-348422f547fa.png)

You can then delete the page:
![grafik](https://user-images.githubusercontent.com/44204527/82872124-e3f6b980-9f32-11ea-82d6-49d688839367.png)

**Comment by santiagoinfantinom** [comment]
Hi @smartie2076, I think I'm not included in the contributors list of this Repo, and I cannot delete any pages. Can you add me?  
Another Question: How can I preview the readthedocs directly from Github?

**Comment by smartie2076** [comment]
> Hi @smartie2076, I think I'm not included in the contributors list of this Repo, and I cannot delete any pages. Can you add me?

Hi @santiagoinfantinom I changed you now to a "maintainer" of the repro - can you delete pages now? 

> Another Question: How can I preview the readthedocs directly from Github?

I am not sure what you mean. Do you want to look at the .rst file? That will be by just looking at the rst file:

![grafik](https://user-images.githubusercontent.com/44204527/82886416-c7fd1300-9f46-11ea-9d08-8a8e1e916b30.png)

Or do you want the html website of readthedocs, including the changes that you want to apply on a specific branch? Then you would log in to readthedocs with your github account, and create a new build environment here ("Activate a version"): https://readthedocs.org/projects/offgridders/versions/
Then you can build that version here: https://readthedocs.org/projects/offgridders/

**Comment by santiagoinfantinom** [comment]
@smartie2076 I still can't erase the pages. Maybe it's just fur contributors?
Thanks for the link by the way. I needed the html website :)

**Comment by smartie2076** [comment]
Glad to help :)

I changed your role to admin now - does it work with that?

**Comment by santiagoinfantinom** [comment]
@smartie2076 Now it works. Thank you! I'll be doing this later today

**Comment by santiagoinfantinom** [comment]
@smartie2076 While deleting  the unused pages I realized that in the "Home"-Page the name oesmot appears instead of offgridders. Additionally 3 new pages appeared after deleting the original structure: Home, Installation and Multi-Criteria Analysis. Should they belong to the readthedocs? They also refer to oesmot. Was that the old name of the proyect or was it like an old template?
I did a new push with some cosmetics changes and with the replacement of oesmot for offgridders on the home page

**Comment by smartie2076** [comment]
Yes @santiagoinfantinom *oesmot* (amonst others) were intermediary names for Offgridders - it is good if you replace those names by the current (and final) one ;)

Please copy the information of the *Home, Installation and Multi-Criteria Analysis* into rst files - I will need to check them seperately to be able to say if they are still correct. Same goes for all of the rst file content anyway (see #61).

**Comment by smartie2076** [comment]
I am not sure if you just pushed on the old branch fix/readthedocs, of if you ment a PR request. If you need a review on your changes/fixed, you should create the draft pull request and then I will check it. 

Please do not use your admin privileges to merge your own PR requests into dev ;)

**Comment by santiagoinfantinom** [comment]
> I am not sure if you just pushed on the old branch fix/readthedocs, of if you ment a PR request.

I meant a push to the old branch. fix/readthedocs is my origin branch for the Wiki/readthedocs. I'll do then another draft PR to dev, but off course not mergining it myself without review :)

>Please copy the information of the Home, Installation and Multi-Criteria Analysis into rst files - I will need to check them seperately to be able to say if they are still correct. Same goes for all of the rst file content anyway (see #61).

After doing this!

**Comment by smartie2076** [comment]
> I meant a push to the old branch. fix/readthedocs is my origin branch for the Wiki/readthedocs. I'll do then another draft PR to dev, but off course not mergining it myself without review :)

Perfect 

> > Please copy the information of the Home, Installation and Multi-Criteria Analysis into rst files - I will need to check them seperately to be able to say if they are still correct. Same goes for all of the rst file content anyway (see #61).
> 
> After doing this!

Copying to rst after this? Okay, good. 
But I think you can not really do #61 ;)

**Comment by santiagoinfantinom** [comment]
I just meant the copying of Home, Installation and Multi-Criteria :)

**Comment by santiagoinfantinom** [comment]
black .code_folder to reformat correctly

**Comment by santiagoinfantinom** [comment]
The last pages were copied to readthedocs and erased from Wiki.
